# Generated by Django 2.0.5 on 2018-06-01 08:54

from django.db import migrations

def load_from_fixture(app, schema_editor):
    from django.core.management import call_command
    call_command("loaddata", "coredata.json")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_from_fixture),
    ]
